site_name: "IFRN/PAR: Horário Acadêmico"

theme:
  name: material
  language: pt

nav:

  - Início: index.md

  - Professor:
    - professor/airton-junior.md
    - professor/alberto-alexandre.md
    - professor/aldayr-dantas.md
    - professor/aline-gomes.md
    - professor/alison-batista.md
    - professor/alvaro-hermano.md
    - professor/ana-rebecca-moura.md
    - professor/andrea-pereira.md
    - professor/andre-gustavo.md
    - professor/antonio-andre.md
    - professor/arlindo-ricarte.md
    - professor/breno-moura.md
    - professor/bruno-gurgel.md
    - professor/carlos-eduardo.md
    - professor/carlos-henrique.md
    - professor/carlos-magno.md
    - professor/carlos-monteiro.md
    - professor/carlos-versiani.md
    - professor/credson-isaac.md
    - professor/dayvyd-lavaniery.md
    - professor/deborah-maia.md
    - professor/diego-pereira.md
    - professor/eduardo-galvao.md
    - professor/elizabete-gurgel.md
    - professor/erika-santos.md
    - professor/fabio-procopio.md
    - professor/francy-izanny.md
    - professor/frank-victor.md
    - professor/givanaldo-rocha.md
    - professor/glenda-marques.md
    - professor/gustavo-fontoura.md
    - professor/gustavo-lima.md
    - professor/henrique-coelho.md
    - professor/higor-morais.md
    - professor/ineuda-lima.md
    - professor/irapuan-medeiros.md
    - professor/jefferson-doolan.md
    - professor/jose-soares-lopes.md
    - professor/jurandy-soares.md
    - professor/kleber-araujo.md
    - professor/leandro-miranda.md
    - professor/lucia-de-fatima.md
    - professor/luiz-alberto.md
    - professor/luiz-ricardo.md
    - professor/marcelo-varela.md
    - professor/maria-aparecida.md
    - professor/marta-silva.md
    - professor/monique-oliveira.md
    - professor/neto-souza.md
    - professor/paulo-morais.md
    - professor/paulo-vitor.md
    - professor/priscila-seabra.md
    - professor/raphael-fontes.md
    - professor/rauryson-bezerra.md
    - professor/rebeka-caroca.md
    - professor/roana-d-avila.md
    - professor/roberto-klecius.md
    - professor/rodrigo-siqueira.md
    - professor/rogerio-alves.md
    - professor/romero-tertulino.md
    - professor/tadeu-ferreira.md
    - professor/thayse-azevedo.md
    - professor/tiago-araujo.md
    - professor/valerio-gutemberg.md
    - professor/victor-costa.md
    - professor/vitor-gaboardi.md
    - professor/wesley-silva.md
    - professor/xenia-brandao.md
    - professor/zulmar-jofli.md

  - Salas:
    - sala/auditorio.md
    - sala/boratorio-de-comandos-eletrohidraulicos-e-eletropneumatic.md
    - sala/ead.md
    - sala/ginasio-poliesportivo.md
    - sala/laboratorio-academia-de-redes-de-computadores.md
    - sala/laboratorio-artes-cenicas.md
    - sala/laboratorio-de-acionamento-de-maquinas.md
    - sala/laboratorio-de-cabeamento-estruturado.md
    - sala/laboratorio-de-eletricidade-e-eletronica.md
    - sala/laboratorio-de-informatica-01.md
    - sala/laboratorio-de-informatica-02.md
    - sala/laboratorio-de-informatica-03.md
    - sala/laboratorio-de-informatica-04.md
    - sala/laboratorio-de-instrumentacao.md
    - sala/laboratorio-de-linguas.md
    - sala/laboratorio-de-manutencao.md
    - sala/laboratorio-de-mecanica-01-usinagem.md
    - sala/laboratorio-de-mecanica-02-metrologia.md
    - sala/laboratorio-de-quimica-e-materiais.md
    - sala/laboratorio-de-redes.md
    - sala/laboratorio-de-robotica.md
    - sala/laboratorio-de-soldagem.md
    - sala/sala-01.md
    - sala/sala-02.md
    - sala/sala-03.md
    - sala/sala-04.md
    - sala/sala-05.md
    - sala/sala-06.md
    - sala/sala-07.md
    - sala/sala-08.md
    - sala/sala-09.md
    - sala/sala-10.md
    - sala/sala-b-11.md
    - sala/sala-b-13.md
    - sala/sala-b-15.md
    - sala/sala-b-16.md
    - sala/sala-de-videoconferencia.md

  - Turmas:
    - turma/dependencia-info-meca-1o-ano-matutino-integrado.md
    - turma/dependencia-info-meca-1o-ano-vespertino-integrado.md
    - turma/dependencia-info-meca-2o-ano-matutino-integrado.md
    - turma/dependencia-info-meca-2o-ano-vespertino-integrado.md
    - turma/ensino-de-artes-e-teatro-1o-per-especializacao.md
    - turma/ensino-de-artes-e-teatro-3o-per-especializacao.md
    - turma/ensino-de-ciencias-e-matematica-1o-per-especializacao.md
    - turma/ensino-de-ciencias-e-matematica-2o-per-especializacao.md
    - turma/ensino-de-ciencias-e-matematica-3o-per-especializacao.md
    - turma/formacao-pedagogica-vespertino-licenciatura.md
    - turma/informatica-1o-ano-matutino-integrado.md
    - turma/informatica-1o-ano-vespertino-integrado.md
    - turma/informatica-2o-ano-matutino-integrado.md
    - turma/informatica-2o-ano-vespertino-integrado.md
    - turma/informatica-3o-ano-matutino-integrado.md
    - turma/informatica-3o-ano-vespertino-integrado.md
    - turma/informatica-4o-ano-matutino-integrado.md
    - turma/informatica-4o-ano-vespertino-integrado.md
    - turma/mecatronica-1o-ano-matutino-integrado.md
    - turma/mecatronica-1o-ano-vespertino-integrado.md
    - turma/mecatronica-1o-per-noturno-subsequente.md
    - turma/mecatronica-2o-ano-matutino-integrado.md
    - turma/mecatronica-2o-ano-vespertino-integrado.md
    - turma/mecatronica-2o-per-noturno-subsequente.md
    - turma/mecatronica-3o-ano-matutino-integrado.md
    - turma/mecatronica-3o-ano-vespertino-integrado.md
    - turma/mecatronica-3o-per-noturno-subsequente.md
    - turma/mecatronica-4o-ano-matutino-integrado.md
    - turma/mecatronica-4o-ano-vespertino-integrado.md
    - turma/mecatronica-4o-per-noturno-subsequente.md
    - turma/redes-de-computadores-1o-per-noturno-subsequente.md
    - turma/redes-de-computadores-2o-per-noturno-subsequente.md
    - turma/redes-de-computadores-3o-per-noturno-subsequente.md
    - turma/redes-de-computadores-4o-per-noturno-subsequente.md
    - turma/sistemas-para-internet-1o-per-matutino-tecnologo.md
    - turma/sistemas-para-internet-3o-per-vespertino-tecnologo.md
    - turma/sistemas-para-internet-5o-per-matutino-tecnologo.md

