# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import time

# -- Project information -----------------------------------------------------

project = 'Horário IFRN/PAR 2021, mód. 4'
copyright = '{}, Antônio Henrique em colaboração com Jurandy Soares'.format(time.strftime('%d/%m/%Y ás %T'))
author = 'Jurandy Soares'

# The full version, including alpha/beta/rc tags
release = '2021.2-mod4'

# New footer
# https://stackoverflow.com/questions/5585250/how-can-i-add-a-custom-footer-to-sphinx-documentation-restructuredtext
# See: _templates/footer.html

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
        'myst_parser',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'pt_BR'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

html_theme_options = {
#        'prev_next_buttons_location': 'top',
        'titles_only': True,
        'collapse_navigation': True,
        'sticky_navigation': False,
        }

html_show_sourcelink = False
html_show_sphinx = False


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

#html_context = {
#        'display_gitlab': True,
#        'theme_vcs_pageview_mode': 'edit/main',
#        'gitlab_host': 'gitlab.devops.ifrn.edu.br',
#        'gitlab_user': 'coapac.par',
#        'gitlab_repo': 'obs-horario',
#        }
